name: Test

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-13
            java: '8'
          - os: macos-15
            java: '8'
          - os: ubuntu-latest
            java: '8'
          - os: ubuntu-24.04-arm
            java: '8'
          - os: windows-latest
            java: '8'

          - os: macos-13
            java: '11'
          - os: macos-15
            java: '11'
          - os: ubuntu-latest
            java: '11'
          - os: ubuntu-24.04-arm
            java: '11'
          - os: windows-latest
            java: '11'
          - os: windows-11-arm
            java: '11'

          - os: macos-13
            java: '17'
          - os: macos-15
            java: '17'
          - os: ubuntu-latest
            java: '17'
          - os: ubuntu-24.04-arm
            java: '17'
          - os: windows-latest
            java: '17'
          - os: windows-11-arm
            java: '17'

          - os: macos-13
            java: '21'
          - os: macos-15
            java: '21'
          - os: ubuntu-latest
            java: '21'
          - os: ubuntu-24.04-arm
            java: '21'
          - os: windows-latest
            java: '21'
          - os: windows-11-arm
            java: '21'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Test
        run: mvn test
